// Team name normalization (same as in Dashboard.jsx)
const TEAM_NAME_DE_MAP = {
  argentina: 'Argentinien',
  australien: 'Australien',
  austria: 'Österreich',
  aegypten: 'Ägypten',
  egypt: 'Ägypten',
  belgium: 'Belgien',
  belgien: 'Belgien',
  bolivia: 'Bolivien',
  bolivien: 'Bolivien',
  'bosnia herzegovina': 'Bosnien-Herzegowina',
  'bosnia hercegovina': 'Bosnien-Herzegowina',
  bosnien: 'Bosnien-Herzegowina',
  'bosnien herzegowina': 'Bosnien-Herzegowina',
  'bosnien hercegowina': 'Bosnien-Herzegowina',
  brazil: 'Brasilien',
  brasilien: 'Brasilien',
  cameroon: 'Kamerun',
  kamerun: 'Kamerun',
  canada: 'Kanada',
  kanada: 'Kanada',
  'cape verde islands': 'Kapverden',
  kapverden: 'Kapverden',
  chile: 'Chile',
  china: 'China',
  colombia: 'Kolumbien',
  kolumbien: 'Kolumbien',
  'congo dr': 'Demokratische Republik Kongo',
  congo: 'Kongo',
  kongo: 'Kongo',
  'costa rica': 'Costa Rica',
  croatia: 'Kroatien',
  kroatien: 'Kroatien',
  curacao: 'Curaçao',
  cyprus: 'Zypern',
  zypern: 'Zypern',
  'czech republic': 'Tschechien',
  czechia: 'Tschechien',
  tschechien: 'Tschechien',
  denmark: 'Dänemark',
  daenemark: 'Dänemark',
  danemark: 'Dänemark',
  ecuador: 'Ecuador',
  england: 'England',
  estonia: 'Estland',
  estland: 'Estland',
  finland: 'Finnland',
  finnland: 'Finnland',
  france: 'Frankreich',
  frankreich: 'Frankreich',
  gabon: 'Gabun',
  gabun: 'Gabun',
  georgia: 'Georgien',
  georgien: 'Georgien',
  germany: 'Deutschland',
  deutschland: 'Deutschland',
  ghana: 'Ghana',
  greece: 'Griechenland',
  griechenland: 'Griechenland',
  guinea: 'Guinea',
  haiti: 'Haiti',
  honduras: 'Honduras',
  hungary: 'Ungarn',
  ungarn: 'Ungarn',
  iceland: 'Island',
  island: 'Island',
  india: 'Indien',
  indien: 'Indien',
  indonesia: 'Indonesien',
  indonesien: 'Indonesien',
  iran: 'Iran',
  iraq: 'Irak',
  irak: 'Irak',
  ireland: 'Irland',
  irland: 'Irland',
  israel: 'Israel',
  italy: 'Italien',
  italien: 'Italien',
  ivory_coast: 'Elfenbeinküste',
  elfenbeinkueste: 'Elfenbeinküste',
  elfenbeinkuste: 'Elfenbeinküste',
  jamaica: 'Jamaika',
  jamaika: 'Jamaika',
  japan: 'Japan',
  jordan: 'Jordanien',
  jordanien: 'Jordanien',
  kazakhstan: 'Kasachstan',
  kasachstan: 'Kasachstan',
  kenya: 'Kenia',
  kenia: 'Kenia',
  kosovo: 'Kosovo',
  kuwait: 'Kuwait',
  kyrgyzstan: 'Kirgistan',
  kirgistan: 'Kirgistan',
  latvia: 'Lettland',
  lettland: 'Lettland',
  lebanon: 'Libanon',
  libanon: 'Libanon',
  lesotho: 'Lesotho',
  liberia: 'Liberia',
  libya: 'Libyen',
  libyen: 'Libyen',
  liechtenstein: 'Liechtenstein',
  lithuania: 'Litauen',
  litauen: 'Litauen',
  luxembourg: 'Luxemburg',
  luxemburg: 'Luxemburg',
  malta: 'Malta',
  mali: 'Mali',
  mexico: 'Mexiko',
  mexiko: 'Mexiko',
  moldova: 'Moldawien',
  moldawien: 'Moldawien',
  monaco: 'Monaco',
  montenegro: 'Montenegro',
  morocco: 'Marokko',
  marokko: 'Marokko',
  mozambique: 'Mosambik',
  mosambik: 'Mosambik',
  namibia: 'Namibia',
  netherlands: 'Niederlande',
  niederlande: 'Niederlande',
  'new zealand': 'Neuseeland',
  neuseeland: 'Neuseeland',
  nicaragua: 'Nicaragua',
  niger: 'Niger',
  nigeria: 'Nigeria',
  'north korea': 'Nordkorea',
  nordkorea: 'Nordkorea',
  'north macedonia': 'Nordmazedonien',
  nordmazedonien: 'Nordmazedonien',
  norway: 'Norwegen',
  norwegen: 'Norwegen',
  oman: 'Oman',
  panama: 'Panama',
  paraguay: 'Paraguay',
  peru: 'Peru',
  philippines: 'Philippinen',
  philippinen: 'Philippinen',
  poland: 'Polen',
  polen: 'Polen',
  portugal: 'Portugal',
  qatar: 'Katar',
  katar: 'Katar',
  romania: 'Rumänien',
  rumaenien: 'Rumänien',
  rumänien: 'Rumänien',
  russia: 'Russland',
  russland: 'Russland',
  'saudi arabia': 'Saudi-Arabien',
  'saudi arabien': 'Saudi-Arabien',
  scotland: 'Schottland',
  schottland: 'Schottland',
  senegal: 'Senegal',
  serbia: 'Serbien',
  serbien: 'Serbien',
  singapore: 'Singapur',
  singapur: 'Singapur',
  slovakia: 'Slowakei',
  slowakei: 'Slowakei',
  slovenia: 'Slowenien',
  slowenien: 'Slowenien',
  'south africa': 'Südafrika',
  suedafrika: 'Südafrika',
  südafrika: 'Südafrika',
  'south korea': 'Südkorea',
  suedkorea: 'Südkorea',
  südkorea: 'Südkorea',
  sudkorea: 'Südkorea',
  spain: 'Spanien',
  spanien: 'Spanien',
  sudan: 'Sudan',
  suriname: 'Surinam',
  surinam: 'Surinam',
  sweden: 'Schweden',
  schweden: 'Schweden',
  switzerland: 'Schweiz',
  schweiz: 'Schweiz',
  syria: 'Syrien',
  syrien: 'Syrien',
  taiwan: 'Taiwan',
  tajikistan: 'Tadschikistan',
  tadschikistan: 'Tadschikistan',
  tanzania: 'Tansania',
  tansania: 'Tansania',
  thailand: 'Thailand',
  togo: 'Togo',
  'trinidad and tobago': 'Trinidad und Tobago',
  'trinidad und tobago': 'Trinidad und Tobago',
  tunisia: 'Tunesien',
  tunesien: 'Tunesien',
  turkey: 'Türkei',
  turkei: 'Türkei',
  tuerkei: 'Türkei',
  turkmenistan: 'Turkmenistan',
  uganda: 'Uganda',
  ukraine: 'Ukraine',
  'united arab emirates': 'Vereinigte Arabische Emirate',
  'vereinigte arabische emirate': 'Vereinigte Arabische Emirate',
  'united kingdom': 'Vereinigtes Königreich',
  'vereinigtes koenigreich': 'Vereinigtes Königreich',
  'united states': 'Vereinigte Staaten',
  usa: 'Vereinigte Staaten',
  'vereinigte staaten': 'Vereinigte Staaten',
  uruguay: 'Uruguay',
  uzbekistan: 'Usbekistan',
  venezuela: 'Venezuela',
  vietnam: 'Vietnam',
  wales: 'Wales',
  zambia: 'Sambia',
  zimbabwe: 'Simbabwe'
};

function normalizeTeamName(teamName) {
  return (teamName || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function getGermanTeamName(teamName) {
  const normalized = normalizeTeamName(teamName);
  return TEAM_NAME_DE_MAP[normalized] || teamName;
}

const TEAM_COLORS = {
  Ägypten: '#ce1126',
  Algerien: '#ef2b2d',
  Argentinien: '#74acdf',
  Australien: '#00843d',
  Österreich: '#ed2939',
  Belgien: '#ffc400',
  Bolivien: '#ce1126',
  Bosnien: '#1d3557',
  Brasilien: '#009c3b',
  'Costa Rica': '#002d62',
  Chile: '#0039a6',
  China: '#ef3340',
  Curaçao: '#2a5599',
  Dänemark: '#c60c30',
  Demokratische: '#ce1126',
  Deutschland: '#000000',
  Ecuador: '#ffc400',
  Elfenbeinküste: '#f47920',
  England: '#012169',
  Estland: '#4891d9',
  Finnland: '#003580',
  Frankreich: '#002395',
  Gabun: '#003d7a',
  Georgien: '#d00c12',
  Ghana: '#ce1126',
  Griechenland: '#0d47a1',
  Guinea: '#007a5e',
  Haiti: '#003da5',
  Honduras: '#003da5',
  Ungarn: '#ce2b37',
  Island: '#002868',
  Indien: '#ff9933',
  Indonesien: '#e60000',
  Iran: '#239f46',
  Irak: '#7c1c05',
  Irland: '#1e90ff',
  Israel: '#0038b8',
  Italien: '#009246',
  Jamaika: '#007659',
  Japan: '#bc002d',
  Jordanien: '#000000',
  Kamerun: '#007a5e',
  Kanada: '#ff0000',
  Kapverden: '#003da5',
  Katar: '#8b0000',
  Kasachstan: '#00afca',
  Kenia: '#000000',
  Kirgistan: '#ff0000',
  Kolumbien: '#ffc400',
  Kongo: '#239f46',
  Kroatien: '#002395',
  Lettland: '#a52a2a',
  Libanon: '#ce1126',
  Lesotho: '#ffffff',
  Liberia: '#003da5',
  Libyen: '#239f46',
  Liechtenstein: '#002395',
  Litauen: '#ffcc00',
  Luxemburg: '#00afca',
  Malta: '#ffffff',
  Mali: '#007a5e',
  Marokko: '#c60c30',
  Mexiko: '#006341',
  Moldawien: '#002395',
  Monaco: '#ef2b2d',
  Montenegro: '#002395',
  Mosambik: '#009246',
  Namibia: '#007a5e',
  Neuseeland: '#000000',
  Niederlande: '#ff6600',
  Nicaragua: '#003da5',
  Niger: '#007a5e',
  Nigeria: '#007a5e',
  Nordkorea: '#ffcc00',
  Nordmazedonien: '#d80000',
  Norwegen: '#ba0c2f',
  Oman: '#ce1126',
  Panama: '#ef4444',
  Paraguay: '#ce1126',
  Peru: '#ce1126',
  Philippinen: '#ffffff',
  Polen: '#dc143c',
  Portugal: '#005600',
  Rumänien: '#002395',
  Russland: '#ffffff',
  'Saudi-Arabien': '#007a5e',
  Schottland: '#002395',
  Schweden: '#ffcc00',
  Schweiz: '#c60c30',
  Senegal: '#007a5e',
  Serbien: '#c60c30',
  Singapur: '#ffffff',
  Slowakei: '#0b4f8c',
  Slowenien: '#002395',
  Spanien: '#c60c30',
  Sudan: '#000000',
  Surinam: '#007a5e',
  Syrien: '#ce1126',
  Taiwan: '#0052cc',
  Tadschikistan: '#ce1126',
  Tansania: '#239f46',
  Thailand: '#ce1126',
  Togo: '#007a5e',
  'Trinidad und': '#ce1126',
  Tunesien: '#ce1126',
  Türkei: '#c60c30',
  Turkmenistan: '#239f46',
  Uganda: '#000000',
  Ukraine: '#ffcc00',
  'Vereinigte Arabische': '#000000',
  'Vereinigtes Königreich': '#012169',
  'Vereinigte Staaten': '#3c3b6b',
  Uruguay: '#38bdf8',
  Usbekistan: '#ce1126',
  Venezuela: '#ffcc00',
  Vietnam: '#ce1126',
  Wales: '#c8102e',
  'Zypern': '#0052cc',
  Sambia: '#000000',
  Simbabwe: '#000000'
};

function hexToRgba(hex, alpha) {
  const normalized = hex.replace('#', '');
  const full = normalized.length === 3
    ? normalized.split('').map((char) => char + char).join('')
    : normalized;

  const r = parseInt(full.slice(0, 2), 16);
  const g = parseInt(full.slice(2, 4), 16);
  const b = parseInt(full.slice(4, 6), 16);

  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function getTeamColor(teamName) {
  const germanTeamName = getGermanTeamName(teamName);
  return TEAM_COLORS[germanTeamName] || '#334155';
}

export function getMatchThemeStyle(homeTeam, awayTeam) {
  const homeColor = getTeamColor(homeTeam);
  const awayColor = getTeamColor(awayTeam);

  return {
    background: `linear-gradient(135deg, ${hexToRgba(homeColor, 0.18)} 0%, ${hexToRgba(homeColor, 0.08)} 40%, ${hexToRgba(awayColor, 0.08)} 60%, ${hexToRgba(awayColor, 0.18)} 100%)`,
    borderColor: homeColor,
    borderWidth: '2px'
  };
}
